# Generated by Django 5.0.1 on 2024-02-03 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('shipping_cost', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.manufacture')),
            ],
        ),
    ]
